/**
 * Codegen: Flow document  ->  runnable Playwright test source.
 *
 * This is the "behind the scenes" magic of a codeless tool — the QA never
 * sees this file, but it's what actually drives the browser.
 */
import type { Assertion, Flow, Locator, Step } from "./flowSchema.js";

/** Strip newlines so flow metadata can't inject code into generated comment lines. */
function safe(s: string): string {
  return s.replace(/[\r\n]/g, " ");
}

function nthSuffix(l: Locator): string {
  if (l.nth === undefined) return "";
  return l.nth === 0 ? ".first()" : `.nth(${l.nth})`;
}

function loc(l: Locator): string {
  const sfx = nthSuffix(l);
  switch (l.strategy) {
    case "role": {
      const opts: string[] = [];
      if (l.name) opts.push(`name: ${JSON.stringify(l.name)}`);
      if (l.exact) opts.push("exact: true");
      return opts.length
        ? `page.getByRole(${JSON.stringify(l.value)}, { ${opts.join(", ")} })${sfx}`
        : `page.getByRole(${JSON.stringify(l.value)})${sfx}`;
    }
    case "text":
      return l.exact
        ? `page.getByText(${JSON.stringify(l.value)}, { exact: true })${sfx}`
        : `page.getByText(${JSON.stringify(l.value)})${sfx}`;
    case "label":
      return l.exact
        ? `page.getByLabel(${JSON.stringify(l.value)}, { exact: true })${sfx}`
        : `page.getByLabel(${JSON.stringify(l.value)})${sfx}`;
    case "placeholder":
      return `page.getByPlaceholder(${JSON.stringify(l.value)})${sfx}`;
    case "testid":
      return `page.getByTestId(${JSON.stringify(l.value)})${sfx}`;
    case "css":
      return `page.locator(${JSON.stringify(l.value)})${sfx}`;
  }
}

function assertion(a: Assertion): string {
  switch (a.kind) {
    case "visible":
      return `await expect(${loc(a.target)}).toBeVisible();`;
    case "hidden":
      return `await expect(${loc(a.target)}).toBeHidden();`;
    case "text":
      return `await expect(${loc(a.target)}).toHaveText(${JSON.stringify(a.expected)});`;
    case "url":
      return `await expect(page).toHaveURL(${JSON.stringify(a.expected)});`;
    case "count":
      return `await expect(${loc(a.target)}).toHaveCount(${a.expected});`;
  }
}

function emitStep(step: Step, depth: number): string[] {
  const pad = "  ".repeat(depth + 1);
  const lines: string[] = [];
  if (step.label) lines.push(`${pad}// ${step.label}`);

  switch (step.type) {
    case "navigate":
      lines.push(`${pad}await page.goto(${JSON.stringify(step.url ?? "/")});`);
      break;
    case "click":
      if (step.target) lines.push(`${pad}await ${loc(step.target)}.click();`);
      break;
    case "fill":
      if (step.target)
        lines.push(`${pad}await ${loc(step.target)}.fill(${JSON.stringify(step.text ?? "")});`);
      break;
    case "assert":
      if (step.assertion) lines.push(`${pad}${assertion(step.assertion)}`);
      break;
    case "apiCall":
      if (step.api) {
        const opts = step.api.body
          ? `, { data: ${JSON.stringify(step.api.body)} }`
          : "";
        lines.push(
          `${pad}const res = await request.${step.api.method.toLowerCase()}(${JSON.stringify(
            step.api.url
          )}${opts});`
        );
        if (step.api.expectStatus != null)
          lines.push(`${pad}expect(res.status()).toBe(${step.api.expectStatus});`);
      }
      break;
    case "loop": {
      const v = step.loop?.as ?? "row";
      if (step.loop?.source === "range") {
        lines.push(`${pad}for (let ${v} = 0; ${v} < ${step.loop.count ?? 1}; ${v}++) {`);
      } else {
        const data = JSON.stringify(step.loop?.dataset ?? []);
        lines.push(`${pad}for (const ${v} of ${data}) {`);
      }
      for (const child of step.children ?? []) lines.push(...emitStep(child, depth + 1));
      lines.push(`${pad}}`);
      break;
    }
    case "if": {
      if (step.condition) {
        const count = `await ${loc(step.condition.target)}.count()`;
        const cmp = step.condition.present ? ">" : "===";
        lines.push(`${pad}if ((${count}) ${cmp} 0) {`);
        for (const child of step.children ?? []) lines.push(...emitStep(child, depth + 1));
        lines.push(`${pad}}`);
      }
      break;
    }
  }
  return lines;
}

export function generatePlaywright(flow: Flow): string {
  const body = flow.steps.flatMap((s) => emitStep(s, 1)).join("\n");
  const usesRequest = JSON.stringify(flow.steps).includes('"apiCall"');
  const fixtures = usesRequest ? "{ page, request }" : "{ page }";
  return `import { test, expect } from '@playwright/test';

// Generated by VisualFlow — do not edit by hand.
// Flow: ${safe(flow.name)}${flow.description ? ` — ${safe(flow.description)}` : ""}
test(${JSON.stringify(flow.name)}, async (${fixtures}) => {
${flow.baseUrl ? `  // base URL: ${safe(flow.baseUrl)}\n` : ""}${body}
});
`;
}

/** Wraps click/fill steps in a try/catch that captures page candidates on locator
 *  failure and writes them to healDataPath before re-throwing. Used by the runner
 *  so routes.ts can call the Healer automatically after a failed run. */
function emitStepInstrumented(step: Step, depth: number, healDataPath: string): string[] {
  const pad = "  ".repeat(depth + 1);

  if ((step.type !== "click" && step.type !== "fill") || !step.target) {
    return emitStep(step, depth);
  }

  const baseLines = emitStep(step, depth);
  const commentLines = step.label ? [baseLines[0]] : [];
  const actionLines = step.label ? baseLines.slice(1) : baseLines;

  const meta = JSON.stringify({
    stepId: step.id,
    stepLabel: step.label ?? step.type,
    brokenLocator: step.target,
  });

  return [
    ...commentLines,
    `${pad}try {`,
    ...actionLines.map((l) => `  ${l}`),
    `${pad}} catch (_healErr) {`,
    `${pad}  try {`,
    `${pad}    const _els = await page.evaluate(() => {`,
    `${pad}      const tags = document.querySelectorAll('button,a,input,select,textarea,[data-testid],[role]');`,
    `${pad}      return Array.from(tags).slice(0, 50).map(el => ({`,
    `${pad}        role: el.getAttribute('role') || el.tagName.toLowerCase() || undefined,`,
    `${pad}        name: el.getAttribute('aria-label') || el.getAttribute('name') || undefined,`,
    `${pad}        text: (el.textContent || '').trim().slice(0, 100) || undefined,`,
    `${pad}        testid: el.getAttribute('data-testid') || undefined,`,
    `${pad}      }));`,
    `${pad}    });`,
    `${pad}    writeFileSync(${JSON.stringify(healDataPath)}, JSON.stringify({ ...${meta}, candidates: _els }));`,
    `${pad}  } catch (_) {}`,
    `${pad}  throw _healErr;`,
    `${pad}}`,
  ];
}

/** Like generatePlaywright but instruments click/fill steps to capture heal data on failure.
 *  The generated code is only used internally by the runner — users always see the clean version. */
export function generatePlaywrightForRun(flow: Flow, healDataPath: string): string {
  const body = flow.steps.flatMap((s) => emitStepInstrumented(s, 1, healDataPath)).join("\n");
  const usesRequest = JSON.stringify(flow.steps).includes('"apiCall"');
  const fixtures = usesRequest ? "{ page, request }" : "{ page }";
  return `import { test, expect } from '@playwright/test';
import { writeFileSync } from 'fs';

// Generated by VisualFlow — do not edit by hand.
// Flow: ${safe(flow.name)}${flow.description ? ` — ${safe(flow.description)}` : ""}
test(${JSON.stringify(flow.name)}, async (${fixtures}) => {
${flow.baseUrl ? `  // base URL: ${safe(flow.baseUrl)}\n` : ""}${body}
});
`;
}
